### ISSUE TITLE
Bad formatting in Studio

### ISSUE THREAD

**Issue by tonylukasavage** [tonylukasavage/ti-mocha#1]
Originally reported by @rblalock.

Studio is not properly handling the ANSI codes, and is instead printing them literally. Console output is fine.

![output screenshot](http://content.screencast.com/users/XiDScreencasts/folders/Snagit/media/f328f54f-bcc2-43fb-b99b-e4092798f227/2014-01-02_12-31-31.png)

**Comment by tonylukasavage** [comment]
Apparently the builtin eclipse console doesn't support embedded ANSI codes, not even colors. There are Eclipse plugins that provide an ANSI-enabled console, but I'd prefer to have this working without it. The only way to color the TiStudio console appears to be using the specific `Ti.API` calls that do so. I'm going to add a setup option like this to indicate that the reporter should not use ANSI codes at all:

``` javascript
mocha.setup({ ansi: false });
```

This line will be necessary when running the tests against this reporter in TiStudio, otherwise you'll end up with the ANSI codes printed literally as in the screenshot in the original description.

For reference, I opened this ticket to see if TiStudio could support ANSI escape codes by default: [https://jira.appcelerator.org/browse/TISTUD-5979](https://jira.appcelerator.org/browse/TISTUD-5979)

**Comment by mattapperson** [comment]
Useful for many things. I hope it gets accepted

**Comment by tonylukasavage** [comment]
@mattapperson even if it does, it'll probably be a while since it's a new feature that will likely require the packaging if a plugin that potentially affects every bit of output. Not something that will be done in short order.

**Comment by mattapperson** [comment]
that is expected

**Comment by tonylukasavage** [comment]
Kept things simple and added a Studio-optimized reporter called `ti-spec-studio`: [https://github.com/tonylukasavage/ti-mocha/commit/f8c14b8364d87b2a083141842fbeb2d88afa09e5](https://github.com/tonylukasavage/ti-mocha/commit/f8c14b8364d87b2a083141842fbeb2d88afa09e5)

Also added a [reporters section](http://tonylukasavage.com/ti-mocha/#reporters) to the docs site.
