### ISSUE TITLE
wrench must be installed first

### ISSUE THREAD

**Issue by Sophrinix** [tonylukasavage/ti-mocha#12]
Your install script assumes that wrench already exists and will fail if it does not.
my env:
   ➜  ~  npm config list
   ; cli configs
   registry = "https://registry.npmjs.org/"
   ; userconfig /Users/andrewmcelroy/.npmrc
   email = "REDACTED"
   username = "codexlabs"
   ; node bin location = /Users/andrewmcelroy/.nvm/v0.11.10/bin/node
   ; cwd = /Users/andrewmcelroy
   ; HOME = /Users/andrewmcelroy

shell history showing the problem.

➜  ~  npm install -g ti-mocha
npm http GET https://registry.npmjs.org/ti-mocha
npm http 304 https://registry.npmjs.org/ti-mocha

ti-mocha@0.1.0 install /Users/andrewmcelroy/.nvm/v0.11.10/lib/node_modules/ti-mocha
 node ./lib/install.js

module.js:333
    throw err;
          ^
Error: Cannot find module 'wrench'
    at Function.Module._resolveFilename (module.js:331:15)
    at Function.Module._load (module.js:273:25)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/Users/andrewmcelroy/.nvm/v0.11.10/lib/node_modules/ti-mocha/lib/install.js:4:11)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Function.Module.runMain (module.js:490:10)
npm ERR! ti-mocha@0.1.0 install: `node ./lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ti-mocha@0.1.0 install script.
npm ERR! This is most likely a problem with the ti-mocha package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./lib/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ti-mocha
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.0.0
npm ERR! command "/Users/andrewmcelroy/.nvm/v0.11.10/bin/node" "/Users/andrewmcelroy/.nvm/v0.11.10/bin/npm" "install" "-g" "ti-mocha"
npm ERR! cwd /Users/andrewmcelroy
npm ERR! node -v v0.11.10
npm ERR! npm -v 1.3.22
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/andrewmcelroy/npm-debug.log
npm ERR! not ok code 0
➜  ~  npm install -g wrench
npm http GET https://registry.npmjs.org/wrench
npm http 304 https://registry.npmjs.org/wrench
wrench@1.5.6 /Users/andrewmcelroy/.nvm/v0.11.10/lib/node_modules/wrench
➜  ~  npm install -g ti-mocha
npm http GET https://registry.npmjs.org/ti-mocha
npm http 304 https://registry.npmjs.org/ti-mocha

> ti-mocha@0.1.0 install /Users/andrewmcelroy/.nvm/v0.11.10/lib/node_modules/ti-mocha
> node ./lib/install.js

ti-mocha@0.1.0 /Users/andrewmcelroy/.nvm/v0.11.10/lib/node_modules/ti-mocha

**Comment by tonylukasavage** [comment]
Why are you installing it globally?

**Comment by Sophrinix** [comment]
A) lazyness.  B) it is inside a VM for a project that I'll announce in the next few days. I want to finish it before I run my mouth. :-)
