### ISSUE TITLE
Does not cooperate with tishadow

### ISSUE THREAD

**Issue by sdobz** [tonylukasavage/ti-mocha#19]
Using the https://github.com/aetheon/ti.mocha.example project I can run ti-mocha

```
git clone https://github.com/aetheon/ti.mocha.example
cd ti.mocha.example
ti build -p ios -I 7.1
```

```
[DEBUG] Application booted in 30.752957 ms
  ti-mocha
    suite 1
      o shows passing tests (fast):
      + shows passing tests (fast)
      o shows passing tests (slow):
      + shows passing tests (slow) (1502ms)
    suite 2
      - shows pending tests
      o fails a test:
      + fails a test


  3 passing (2s)
  1 pending
```

But running tishadow I get issues:

```
tishadow run
```

```
[ERROR] [iphone, 7.1, 192.168.2.179] Couldn't find module: mocha
[ERROR] [iphone, 7.1, 192.168.2.179]
Type: TypeError
Message: 'undefined' is not a constructor (evaluating 'new Mocha({
        reporter: "html"
    })')
File: /ti-mocha.js.js
Line: 2783
[ERROR] [iphone, 7.1, 192.168.2.179] ReferenceError: Can't find variable: describe
```

From what I have seen supporting tishadow is a pain, but it would be so convenient...
Good luck!

**Comment by tonylukasavage** [comment]
I'm assuming this has to do with tishadow not loading mocha into the current context. I have no control over this and this should be addressed in [tishadow](https://github.com/dbankier/TiShadow/issues?state=open), not here. You'll want to create a similar ticket there.

**Comment by sdobz** [comment]
If anyone else arrives here wondering how to get it to work I did a find/replace and changed `require` to `require3` which somehow fixed it.

**Comment by nicka** [comment]
@sdobz could you give some more information about this? Where exactly did you change `require`? Did you change it for `require('ti-mocha');`?

**Comment by sdobz** [comment]
After various debugging and poking around I got the feeling that the require defined here and the require defined by titanium were conflicting because of tishadow. I replaced every occurrence of  "require" in ti-mocha.js with require3, an arbitrary choice. I did not use it very thoroughly, sadly my deadlines are such that I'm scrambling to get my code working much less tested.
