### ISSUE TITLE
Doc site is down

### ISSUE THREAD

**Issue by onury** [tonylukasavage/ti-mocha#25]
http://tonylukasavage.com/ti-mocha/  displays "Site Disabled" (due to misconfiguration).

**Comment by tonylukasavage** [comment]
thanks for the heads up, ill get it fixed

**Comment by gmuresan** [comment]
Is there any news about the doc site status?

**Comment by tonylukasavage** [comment]
up and running again

**Comment by mattapperson** [comment]
Down again
