### ISSUE TITLE
debug method does nothing

### ISSUE THREAD

**Issue by mattapperson** [tonylukasavage/ti-mocha#27]
No really, it does nothing...

``` javascript
require.register("browser/debug.js", function(module, exports, require){

module.exports = function(type){
 return function(){
 }
};

}); // module: browser/debug.js
```

**Comment by tonylukasavage** [comment]
eh, this is generated code and not really worth the effort to remove. That said, a simple PR (not something that slices up an AST) would be acceptable. I'm closing in the meantime, but will reopen if someone wants to address it.

**Comment by mattapperson** [comment]
@tonylukasavage Not something I am willing to PR at this point. but FWIW the reason this is an issue is not to remove it, but because mocha tries to for debugging.  So it should really use console.log or something

**Comment by tonylukasavage** [comment]
@mattapperson I see what you're saying, but in the case of ti-mocha, the only supported reporters are the ones in the repo right now, and they don't leverage `debug()`, so it's not an issue. That said, again, I'm fine with a PR that would in theory make ti-mocha more compatible with existing reporters in mocha.
