### ISSUE TITLE
app crash when use shouldjs in testing async func

### ISSUE THREAD

**Issue by vilix13** [tonylukasavage/ti-mocha#30]
Sorry for my english, but I'll try to describe the problem a failure code below:

```
describe('download root page', function() {

  it('must return success status', function(done) {
    var url = 'htstp://bbc.com/news';
    u.downloadPage(url, function(status) {
      // if (status != 'success') {
      //   err = new Error('error');
      //   return done(err);
      // }
      status.should.equal('success');
      done();
    });
  });
});
```

When url valid, test passed. But when url not valid my app crash:

```
 utils.js
    download root page
      o must return success status: 
[DEBUG] [ioslib] [ios-sim] [DEBUG] Session did end with error (null)
[DEBUG] [ioslib] [ios-sim] [DEBUG] Removing named pipe at `/var/folders/fn/49fp5hx941541w0ncv5n28_h0000gn/T//ios-sim-stderr-pipe-1429636427'
[DEBUG] [ioslib] [ios-sim] [DEBUG] Removing named pipe at `/var/folders/fn/49fp5hx941541w0ncv5n28_h0000gn/T//ios-sim-stdout-pipe-1429636427'
[DEBUG] [ioslib] [ios-sim] Exited with code: 0
```

When I use commented code and delete `status.should.equal('success');` all work good, but I want use BDD style assertions. Thx

**Comment by yuchi** [comment]
This is an issue caused by the absence of an event for uncaught exceptions on Titanium.

You can wrap your code in a `function(){ ... }.should.not.throw()`.

**Comment by vilix13** [comment]
Thank you very much for help) But I do not quite understand what I need wrap. I try like this:

```
(function() {status.should.equal('success');}).should.not.throw();
```

But this crash app too

**Comment by yuchi** [comment]
Gosh, I’m sorry, obviously you just get a new error.

Could you try this one please:

``` js
it('……', function () {
  var url = 'htstp://bbc.com/news';
  u.downloadPage(url, function(status) {
    try {
      status.should.equal('success');
    }
    catch (e) {
      return done(e);
    }
    done();
  });
});
```

**Comment by vilix13** [comment]
oh thank you) that work) But I understand my bad, I did not read http://tonylukasavage.com/ti-mocha/ .
More efficient answer for my question:

```
it('……', function () {
  var url = 'htstp://bbc.com/news';
  u.downloadPage(url, function(status) {
    should(status).equal('success');
    done();
  });
});
```

but `should(f.exists()).equal(true);` crash app. 
Your answer works in both cases, and I will use it. Thank you again)
