### ISSUE TITLE
Test createController?

### ISSUE THREAD

**Issue by m1ga** [tonylukasavage/ti-mocha#31]
How can I test if a new controller gets created in an alloy project?

In my code I have (index.js)

```
Alloy.createController("request");
```

and it will create a new window. Now I want to check if the window is open and want to access its elements.

my test for index.js:

```
// Create a test suite
describe("test1", function() {
    var Alloy = require("alloy");
    var $;
    beforeEach(function() {
        $ = Alloy.createController("index");
    });

    describe("can create and destroy", function() {
        it("show request window", function() {
            $.__views.btn_requests.fireEvent("click");
            waits(500);
            runs(function () {
                //$ = Alloy.createController("requests"); // will create a 2nd window
                //expect(??).toBe(true);    // what do I need to check
            });
        });
    });
});
```

it will click the button and the button will run the createController code => the window opens. But now I can't access its elements and don't know how to test if the window is visible. When I run

```
$ = Alloy.createController("requests");
```

in my spec it will create a second window in my app.

Is it the wrong approach I'm trying?

**Comment by tonylukasavage** [comment]
If you want to inspect anything in the created controller, then you need to attach those elements to the controller. This is done automatically via Alloy's markup, but if you are created these elements programmatically, you'll need to manually attach them to the created controller. Then you should be able to access them by id or with `getView()`.
