### ISSUE TITLE
Not able to Automate ti-mocha tests

### ISSUE THREAD

**Issue by nagarajdevendhiran** [tonylukasavage/ti-mocha#33]
Hi,

I am trying to automate ti-mocha tests using a Grunt build script and Appcelerator CLI.

As ti-mocha tests run from within the Appc alloy app, the tests are always executed when the app runs.

I would like to find out if there is a way to run ti-mocha test conditionally for e.g. by passing a flag as a part of the build arguments to Appcelerator CLI.

I'm using below command to run the app using CLI.

appc run -p ios

Please help me out of this.

**Comment by tonylukasavage** [comment]
There is no built-in test automation in the appc cli. What I would suggest is perhaps setting a property in your tiapp.xml to indicate that you want to run your tests, then checking for that property at runtime to determine whether or not to run your tests. Check the docs on [Titanium.App.Properties](https://docs.appcelerator.com/platform/latest/#!/api/Titanium.App.Properties) for details on how you can do that.

You may also want to make an issue with the titanium cli or appcelerator cli projects to request, as a feature, that you be able to specify a tiapp.xml property at the cli. For example, something like this would prevent you from having to make the update in the tiapp.xml file yourself:

```
appc run -p ios --property "ti-mocha-test=1"
```
