### ISSUE TITLE
npm install script to add ti-mocha.js to your Resources

### ISSUE THREAD

**Issue by tonylukasavage** [tonylukasavage/ti-mocha#5]
Seeing as how Titanium doesn't reference the `node_modules` folder, but I still want to be able to distribute ti-mocha via npm, it would be nice if there was a simple post-install script to put ti-mocha.js in the developer's Resources folder.

**Comment by mattapperson** [comment]
What about throwing it into a global native JS module instead?

**Comment by tonylukasavage** [comment]
I like the idea of it, but I want to keep the install local. AFAIK, there's no way to detect a global (`-g`) npm install in the install script. I could probably check to see if `process.cwd()` ends in `node_modules/ti-mocha`, indicating that the install script was called, but that's pretty ugly.
